### PR TITLE
Types and entrypoint

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
### What this PR does

- Exports types that we were not exporting from the entrypoint, this is needed because otherwise devs would have to import things from `package-manager-manager/dist/...` for example like so: Screenshot at 2023-10-15 18-01-17

- Make the output a single js bundle (besides still maintaining both `esm` and `cjs`) so that people actually can't import directly from `dist` giving us more control over what's actually exported from the library (without this basically everything exported in a ts file, even internal utilities would just be importable from users of the library)

### CODE REVIEW

**Comment by james-elicx** [comment]
Why are you importing from `/dist/commands`? If something should be available at `/`, it should be exported from the `index.ts`. If another path should be usable like `/commands`, it should be added to the `package.json` exports field.

I'm not sure I understand the point

**Comment by dario-piotrowicz** [comment]
> Why are you importing from `/dist/commands`? If something should be available at `/`, it should be exported from the `index.ts`. If another path should be usable like `/commands`, it should be added to the `package.json` exports field.
> 
> I'm not sure I understand the point

Sorry I must have written the description in a confusing way :sweat: 

I was saying the exact same thing you are, I'm exporting the types at `/` because they should be but currently are not

Right now if users of the package wanted to use those types they'd be forced to import from `/dist/command` since the types are not properly exported at `/`

I 10000% agree with you people should not export from `/dist/commands`, that's the whole point here

(and regarding the build output change, that's to make sure that there actually isn't a `/dist` path for users to import from)

**Comment by james-elicx** [comment]
> > Why are you importing from `/dist/commands`? If something should be available at `/`, it should be exported from the `index.ts`. If another path should be usable like `/commands`, it should be added to the `package.json` exports field.
> > I'm not sure I understand the point
> 
> Sorry I must have written the description in a confusing way 😓
> 
> I was saying the exact same thing you are, I'm exporting the types at `/` because they should be but currently are not
> 
> Right now if users of the package wanted to use those types they'd be forced to import from `/dist/command` since the types are not properly exported at `/`
> 
> I 10000% agree with you people should not export from `/dist/commands`, that's the whole point here
> 
> (and regarding the build output change, that's to make sure that there actually isn't a `/dist` path for users to import from)

So if exporting the types from / fixes it, I'm not sure I understand why we need to bundle it into a single file?

**Comment by dario-piotrowicz** [comment]
> So if exporting the types from / fixes it, I'm not sure I understand why we need to bundle it into a single file?

Yes exporting from `/` fixes it, so bundling into a single file is an improvement on top of that fix, it's not really needed to fix that issue

I think bundling into a single file is important so that:
 - people don't get the option to import same thing from various multiple different places but just from a single clear well defined entrypoint
 - auto-imports from IDEs don't get confused (I noticed that vscode automatically adds more specific imports, so by default people get imports from `/dist/...` and have to go there and fix them manually, which is quite annoying)
 - when writing code we can be free to export whatever we want in files internally not having to worry that users of the package can import and use them, only what we want to export is actually exposed to the user instead of everything
(e.g. do we really want users of the library to be able to import `getBunGetPackageInfoFuncion`? what for? their IDE can suggest that to them, isn't that just going to cause a worse/more confusing DX?)

So to me bunding into a single file seems to provide quite a few benefits, are there some downsides of bundling into a single file that I'm missing?

**Comment by dario-piotrowicz** [comment]
PS: if later there would be a need to have other import paths for whatever reason (I can't think of any on the top of my head) that could be added alongside an entry in the `exports` field as you mentioned, again giving us full control on what's exported instead of exporting every possible thing

**Review by james-elicx — APPROVED** [review]

**Comment by dario-piotrowicz** [comment]
@james-elicx I've removed the bundling changes as you seem quite not convinced

I really think that version to be better, but I don't want to force my point of view, hopefully we can revisit this at some point 

PS: with "revisit" I mean look into this, not having it my way :sweat_smile: What I would really love is to either have the output all bundled into a single file (which I think it's better) or understand why having multiple output files can have benefits (since on the top of my head I see none)

**Pull request merged**
